### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Ay0hCrypto** [NebraLtd/helium-sensecap#1]
Could you detail how to monitor a SenseCAP running your Software. 
OR provide instruction for ssh(not through balena cloud) so I can pull the logs myself. TY. 
Does this version change the config.json upon the first update/boot ? Having issues accessing the miner through ssh, with a key i know was good when used on other FW packages.
(miner IP will pull up a Diagnostic page, for others looking, shows connection and sync status)

**Comment by shawaj** [comment]
https://nebra.io/sensecap

**Comment by ifeign** [comment]
> https://nebra.io/sensecap

Completely unhelpful

**Comment by shawaj** [comment]
You just need to set it up as per our guide https://helium.nebra.com/#/handy-guides/flash-sd
