### ISSUE TITLE
Fork

### ISSUE THREAD

**Issue by Ay0hCrypto** [NebraLtd/helium-sensecap#2]
If you attempt to Fork the fleet the PacketForwarder container is stuck in restart loop.

- ` packet-forwarder  Traceback (most recent call last):
-  packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
-  packet-forwarder      return _run_code(code, main_globals, None,
-  packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
-  packet-forwarder      exec(code, run_globals)
-  packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
-  packet-forwarder      VARIANT = os.environ['VARIANT']
-  packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
-  packet-forwarder      raise KeyError(key) from None
-  packet-forwarder  KeyError: 'VARIANT'
- Service exited 'packet-forwarder sha256:8fb6af555f8cec6f080be3d6d15ce487305078a957e2851460b8c23c2f91d100'`

**Comment by Ay0hCrypto** [comment]
[03.05.22_00 32 13_(-0400).txt](https://github.com/NebraLtd/helium-sensecap/files/8608275/03.05.22_00.32.13_.-0400.txt)

**Comment by Ay0hCrypto** [comment]
VARIANT                         COMP-SENSECAPM1
REGION_OVERRIDE      us915
 These settings applied to _all systems_ works for NA change **us915** to **eu868**

**Comment by shawaj** [comment]
You don't need to fork this. Just install from https://nebra.io/sensecap and it works out of the box

**Comment by Ay0hCrypto** [comment]
Without forking it, you can't monitor it, access it, see the logs. Amazing job on the cross compatibility.

**Comment by shawaj** [comment]
@Ay0hCrypto most people do not want to do any of those things, they just want it to auto update. If you want to do those things, we do not support that and you are on your own. That's why we suggest to just install from balenaHub.

Also just FYI you don't need a REGION_OVERRIDE if you have asserted the location on the blockchain.

**Comment by Ay0hCrypto** [comment]
Either way totally appreciate it, Great work. Can't wait to see new miner support added.
