### ISSUE TITLE
KeyError: 'VARIANT'

### ISSUE THREAD

**Issue by RoZelm0** [NebraLtd/helium-sensecap#3]
KeyError: 'VARIANT'
 packet-forwarder  Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'
 packet-forwarder  Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'
 packet-forwarder  Traceback (most recent call last):
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
 packet-forwarder      return _run_code(code, main_globals, None,
 packet-forwarder    File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
 packet-forwarder      exec(code, run_globals)
 packet-forwarder    File "/opt/pktfwd/__main__.py", line 13, in <module>
 packet-forwarder      VARIANT = os.environ['VARIANT']
 packet-forwarder    File "/usr/local/lib/python3.10/os.py", line 679, in __getitem__
 packet-forwarder      raise KeyError(key) from None
 packet-forwarder  KeyError: 'VARIANT'

how do i set it up

**Comment by pritamghanghas** [comment]
it has to be exported as an environment variable. In balena you can do that
under device or fleet variables.

**Comment by RoZelm0** [comment]
create a variable if so which ones?

**Comment by shawaj** [comment]
You should install from https://hub.balena.io/nebraltd/helium-sensecap

Then you don't need to set any variant.

You can follow the guide here... https://helium.nebra.com/#/handy-guides/flash-sd

**Comment by shawaj** [comment]
Closing this as not an issue
