### ISSUE TITLE
gateway-config

### ISSUE THREAD

**Issue by RoZelm0** [NebraLtd/helium-sensecap#4]
gateway-config  Traceback (most recent call last):
 gateway-config    File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
 gateway-config      "__main__", mod_spec)
 gateway-config    File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
 gateway-config      exec(code, run_globals)
 gateway-config    File "gatewayconfig/__main__.py", line 77, in <module>
 gateway-config      main()
 gateway-config    File "gatewayconfig/__main__.py", line 30, in main
 gateway-config      start()
 gateway-config    File "gatewayconfig/__main__.py", line 66, in start
 gateway-config      FIRMWARE_VERSION
 gateway-config    File "/opt/gatewayconfig/gatewayconfig_app.py", line 31, in __init__
 gateway-config      self.variant_details = variant_definitions[variant]
 gateway-config  KeyError: None

What should I do.

**Comment by RoZelm0** [comment]
he following ENV variables must be set: FREQ, SENTRY_CONFIG, SENTRY_DIAG, SENTRY_PKTFWD, and VARIANT


it must have something to do with it.

can this be??

**Comment by shawaj** [comment]
See my comment on #3 you just need to install using that method and the environment variables are already set
