### ISSUE TITLE
Failed to build multiplexer and packet forwarder.

### ISSUE THREAD

**Issue by vVxiliVv** [NebraLtd/helium-sensecap#5]
Here is the error when i try to deploy the latest release.

[Info]              Starting build for nebra-sensecap, user g_szil_rd_k_k_ny
[Info]              Dashboard link: https://dashboard.balena-cloud.com/apps/2016434/devices
[Info]              Building on arm02
[Info]              No suitable previous release for caching, skipping cache pull
[Info]              Uploading images
[Success]           Successfully uploaded images
[Error]             Some services failed to build:
[Error]               Service: packet-forwarder
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Error]               Service: multiplexer
[Error]                 Error: no matching manifest for linux/arm64/v8 in the manifest list entries
[Info]              Built on arm02
[Error]             Not deploying release.

Thanks!

**Comment by shawaj** [comment]
@vVxiliVv This is working now, see https://github.com/NebraLtd/helium-rak/issues/19#issuecomment-1418259072

If you are finding our open source software useful then please consider sponsoring our efforts at https://github.com/sponsors/NebraLtd

And please share to others as well 🙂

We have lots of cool features coming up!

**Comment by vVxiliVv** [comment]
Yep, its working now.
Thank you very much for the hard work.
If i would like to move my hotspot or update the antenna, do i use the nebra app from google play?

**Comment by shawaj** [comment]
You can use the Nebra app yes, although the Sensecap app should probably still work also (or probably any of the other vendor apps)

It's only for the initial onboarding that you need to use the vendors open app really :-)

**Comment by shawaj** [comment]
Also @vVxiliVv we are pushing some more important updates soon so you might want to update again in a few days time to make sure everything is working nicely

**Comment by vVxiliVv** [comment]
Thank you very much, i noticed that now i cant seem to turn of bt to make the hotspot more energy effiecnt.
(Diagnostics freaks out and packet forwarder keeps on restarting)
Also i need to set the FREQ variable, altough maybe it wasnt able to get it from miner because it didnt start for the above reasons.

**Comment by shawaj** [comment]
The Bluetooth turns off automatically after 5 minutes.

The FREQ thing was reported separately. We have fixed it now but you can put anything in there. It's actually a parameter that is only used for our own brand Nebra miners. For third party miners you can just put None or whatever your want really

**Comment by shawaj** [comment]
The FREQ fix thing I mentioned will roll out in an update in the next day or two
