### ISSUE TITLE
How much timei t needs to start?

### ISSUE THREAD

**Issue by rampa069** [NebraLtd/helium-sensecap#6]
Flashed an sensecap M1 one hour ago.  i cannot see the web console. (it conencts, but waits forever) how much time can i expect to wait?

**Comment by shawaj** [comment]
You might need to try it again, we just pushed an update that fixed an issue.

Please try to push the latest release

**Comment by rampa069** [comment]
it ended ok. now i have the same version on nebra and on sensecap. (2022.12.13.0-24 (07d9233))

 but im getting error 500 on  the helium tab. (http://nebra-88da1c.local/hnt)

**Comment by shawaj** [comment]
Can you share a screenshot @rampa069 ?

And can you share the diagnostics JSON from the main page?

**Comment by rampa069** [comment]
`{"AN":"melted-brunette-pheasant","BA":"HELIUM-SENSECAP","BALENA_DEVICE_TYPE":["raspberrypi4-64"],"BN":"dawn-violet","BT":true,"BUTTON":27,"CELLULAR":false,"CONTAINS_FCC_IDS":[],"CONTAINS_IC_IDS":[],"CPU_ARCH":"aarch64","E0":"E4:5F:01:88:DA:1C","ECC":true,"ECCOB":true,"FCC_IDS":[],"FR":null,"FRIENDLY":"SenseCAP M1","FW":"2023.02.04.0","IC_IDS":[],"ID":"8c7c14c2403eaed93c3a94f8ba2b5d80","KEY_STORAGE_BUS":"/dev/i2c-1","LOR":true,"LTE":false,"MAC":"wlan0","OK":"111QzHdGo683HUEdbRQKJyya6nQacWn4StdZXiWk2qQwpPPhuyM","PF":true,"PK":"111QzHdGo683HUEdbRQKJyya6nQacWn4StdZXiWk2qQwpPPhuyM","RE":"EU868","RESET":17,"SPIBUS":"spidev0.0","STATUS":22,"SUPPORTED_MODELS":["SenseCAP M1"],"SWARM_KEY_URI":"ecc://i2c-1:96?slot=0","TYPE":"Full","VA":"COMP-SENSECAPM1","W0":"E4:5F:01:88:DA:1D","firmware_short_hash":"b53ac26","last_updated":"18:51 UTC 06 Feb 2023","serial_number":"10000000452eb348"}`


![Captura de pantalla 2023-02-06 a las 19 53 35](https://user-images.githubusercontent.com/955226/217059937-e4f48446-5d13-4fbe-85b6-e88dfa0c411a.png)

**Comment by shawaj** [comment]
@rampa069 could you add gh_shawaj user to the device/fleet on balena so I can take a look?

**Comment by shawaj** [comment]
@rampa069 I can load the /hnt page fine.

Can you try again?

**Comment by rampa069** [comment]
it worked....
