### ISSUE TITLE
How can i manage the device?

### ISSUE THREAD

**Issue by rampa069** [NebraLtd/helium-sensecap#7]
In the readme, stays it will show in my balena cloud apps. but nothing appears... Is there any howto about adding the device?

**Comment by rampa069** [comment]
(only need remote reboot. The hotspot is not sending traffic since 12 hours and don't have it on nebra dashboard)

**Comment by shawaj** [comment]
How did you install the software?

**Comment by shawaj** [comment]
Closing as we have had no response. Please open a new issue if you still have problems
