### ISSUE TITLE
config.json file

### ISSUE THREAD

**Issue by Terrorr** [NebraLtd/helium-sensecap#8]
Do we need to copy config.json file into new sdcard ? There is no info about it in manual

**Comment by shawaj** [comment]
You can just download the SD card image from here...
https://github.com/NebraLtd/helium-sensecap/releases/tag/2023.02.07.0-23-helium-sensecap-2023-03-19-OpenFleet

You can use https://etcher.io to flash to your SD card.

Alternatively, if you want to manage via your own balenaCloud account you can deploy at...
https://hub.balena.io/apps/2025884/helium-sensecap-app

However the second option will mean you have to manage the updates yourself.
