### ISSUE TITLE
after install services dont start 

### ISSUE THREAD

**Issue by oly99** [NebraLtd/helium-sensecap#9]
after install services dont start just loops please see log bellow 

2023-05-16 23:45:49,093 - [WARNING] - hw_diag.utilities.hardware - (api.py).__retry_internal -- /opt/python-dependencies/retry/api.py:(40) - [Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 10 seconds...
 diagnostics  WARNING:hw_diag.utilities.hardware:[Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 10 seconds...
 helium-miner  Diagnostics container not ready. Going to sleep.
Service exited 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
Restarting service 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
 packet-forwarder  Error: Cannot set FREQ variable.
 packet-forwarder  Error: Cannot set VARIANT variable.
 packet-forwarder  Error: Required VARIANT parameter has not been set. Container will be reset after 10 sec.
 diagnostics  2023-05-16 23:45:59,094 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).lora_module_test -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(312) - File /var/pktfwd/diagnostics doesn't exit yet. Most likely pktfwd container hasn't started yet
 diagnostics  ERROR:hw_diag.utilities.hardware:File /var/pktfwd/diagnostics doesn't exit yet. Most likely pktfwd container hasn't started yet
 diagnostics  2023-05-16 23:45:59,095 - [WARNING] - hw_diag.utilities.hardware - (api.py).__retry_internal -- /opt/python-dependencies/retry/api.py:(40) - [Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 15 seconds...
 diagnostics  WARNING:hw_diag.utilities.hardware:[Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 15 seconds...
Service exited 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
Restarting service 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
 packet-forwarder  Error: Cannot set FREQ variable.
 packet-forwarder  Error: Cannot set VARIANT variable.
 packet-forwarder  Error: Required VARIANT parameter has not been set. Container will be reset after 10 sec.
 helium-miner  Diagnostics container not ready. Going to sleep.
 diagnostics  2023-05-16 23:46:14,097 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).lora_module_test -- /opt/python-dependencies/hw_diag/utilities/hardware.py:(312) - File /var/pktfwd/diagnostics doesn't exit yet. Most likely pktfwd container hasn't started yet
 diagnostics  ERROR:hw_diag.utilities.hardware:File /var/pktfwd/diagnostics doesn't exit yet. Most likely pktfwd container hasn't started yet
 diagnostics  2023-05-16 23:46:14,097 - [WARNING] - hw_diag.utilities.hardware - (api.py).__retry_internal -- /opt/python-dependencies/retry/api.py:(40) - [Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 15 seconds...
 diagnostics  WARNING:hw_diag.utilities.hardware:[Errno 2] No such file or directory: '/var/pktfwd/diagnostics', retrying in 15 seconds...
Service exited 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
Restarting service 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
 packet-forwarder  Error: Cannot set FREQ variable.
 packet-forwarder  Error: Cannot set VARIANT variable.
 packet-forwarder  Error: Required VARIANT parameter has not been set. Container will be reset after 10 sec.
Warning: Suppressed 42 message(s) due to rate limiting
 diagnostics           ^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics  FileNotFoundError: [Errno 2] No such file or directory: '/var/pktfwd/diagnostics'
 diagnostics  2023-05-16 23:46:29,139 - [WARNING] - hm_pyhelper.miner_param - (miner_param.py).get_gateway_mfr_command -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(211) - Variant None is not recognized. Omitting --device arg.
 diagnostics  WARNING:hm_pyhelper.miner_param:Variant None is not recognized. Omitting --device arg.
 diagnostics  2023-05-16 23:46:29,146 - [ERROR] - hm_pyhelper.miner_param - (miner_param.py).run_gateway_mfr -- /opt/python-dependencies/hm_pyhelper/miner_param.py:(42) - gateway_mfr exited with a non-zero status
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr_aarch64', 'test']' returned non-zero exit status 2.
 diagnostics  ERROR:hm_pyhelper.miner_param:gateway_mfr exited with a non-zero status
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr_aarch64', 'test']' returned non-zero exit status 2.
 diagnostics  2023-05-16 23:46:29,149 - [ERROR] - hm_pyhelper.miner_param - (ecc_diagnostic.py).perform_test -- /opt/python-dependencies/hw_diag/diagnostics/ecc_diagnostic.py:(65) - gateway_mfr exited with a non-zero status
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr_aarch64', 'test']' returned non-zero exit status 2.
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hw_diag/diagnostics/ecc_diagnostic.py", line 51, in perform_test
 diagnostics      ecc_tests = get_gateway_mfr_test_result()
 diagnostics                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 247, in get_gateway_mfr_test_result
 diagnostics      return run_gateway_mfr("test")
 diagnostics             ^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 71, in wrapper_lock_ecc
 diagnostics      raise ex
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 60, in wrapper_lock_ecc
 diagnostics      raise ex
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 57, in wrapper_lock_ecc
 diagnostics      value = func(*args, **kwargs)
 diagnostics              ^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 43, in run_gateway_mfr
 diagnostics      raise ECCMalfunctionException(err_str).with_traceback(e.__traceback__)
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  hm_pyhelper.exceptions.ECCMalfunctionException: gateway_mfr exited with a non-zero status
 diagnostics  ERROR:hm_pyhelper.miner_param:gateway_mfr exited with a non-zero status
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  subprocess.CalledProcessError: Command '['/opt/python-dependencies/hm_pyhelper/gateway_mfr_aarch64', 'test']' returned non-zero exit status 2.
 diagnostics  
 diagnostics  During handling of the above exception, another exception occurred:
 diagnostics  
 diagnostics  Traceback (most recent call last):
 diagnostics    File "/opt/python-dependencies/hw_diag/diagnostics/ecc_diagnostic.py", line 51, in perform_test
 diagnostics      ecc_tests = get_gateway_mfr_test_result()
 diagnostics                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 247, in get_gateway_mfr_test_result
 diagnostics      return run_gateway_mfr("test")
 diagnostics             ^^^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 71, in wrapper_lock_ecc
 diagnostics      raise ex
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 60, in wrapper_lock_ecc
 diagnostics      raise ex
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/lock_singleton.py", line 57, in wrapper_lock_ecc
 diagnostics      value = func(*args, **kwargs)
 diagnostics              ^^^^^^^^^^^^^^^^^^^^^
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 43, in run_gateway_mfr
 diagnostics      raise ECCMalfunctionException(err_str).with_traceback(e.__traceback__)
 diagnostics    File "/opt/python-dependencies/hm_pyhelper/miner_param.py", line 33, in run_gateway_mfr
 diagnostics      run_gateway_mfr_result = subprocess.run(
 diagnostics                               ^^^^^^^^^^^^^^^
 diagnostics    File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
 diagnostics      raise CalledProcessError(retcode, process.args,
 diagnostics  hm_pyhelper.exceptions.ECCMalfunctionException: gateway_mfr exited with a non-zero status
 diagnostics  2023-05-16 23:46:29,155 - [DEBUG] - hw_diag.diagnostics.bt_diagnostic - (bt_diagnostic.py).perform_test -- /opt/python-dependencies/hw_diag/diagnostics/bt_diagnostic.py:(28) - Retrieving list of Bluetooth device(s)
Warning: Suppressed 13 message(s) due to slow reading
 helium-miner  Diagnostics container not ready. Going to sleep.
Service exited 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
Restarting service 'packet-forwarder sha256:86879d57ab373a0eba294f8a6112a4e58de6b37cc76d20a31060cf3fd8ff29de'
 packet-forwarder  Error: Cannot set FREQ variable.
 packet-forwarder  Error: Cannot set VARIANT variable.
 packet-forwarder  Error: Required VARIANT parameter has not been set. Container will be reset after 10 sec.
 diagnostics  2023-05-16 23:46:34,175 - [ERROR] - hw_diag.utilities.hardware - (hardware.py).lor

**Comment by shawaj** [comment]
Are you running this on your own balenaCloud account?

If so it seems like you haven't set the variant variable correctly (and possibly other settings)

Easiest way is to use the deploy with Balena button on the main repo... https://github.com/NebraLtd/helium-sensecap#helium-sensecap

**Comment by shawaj** [comment]
@oly99 ^^

**Comment by shawaj** [comment]
Did this fix your issue @oly99 ?

**Comment by shawaj** [comment]
Closing as no reply
